<?php
return [
        ## workers ##
        'Contragent',
        'StrategyCases',
        'StrategyFilter',
        'StrategyFilterType',
        'StrategyVariables',
        'TaskTemplates',
        'StrategyCase',
        'StrategySets',
        'Tasks',

        ## models ##
        'Filters',
        'Strategy',
        'StrategyFiter',
        'StrategyPause',
        'StrategySet',
        'StrategySetFilter',
        'StrategyToSet',
        'StrategyItem',
        'StrategyItemFilter',
        'Task',
        'TaskFc',
        'TaskType',
        'Schedule',
        'Filter',
        'Filters',
        'FiltersAll',
        'FiltersContragents',
        'FiltersContragentsAll',

        ## tables ##
        'strategy',
        'strategy_item',
        'strategy_filter',
        'strategy_to_set',
        'strategy_set',
        'strategy_item_filter',
        'task_type',
        'filters',
        'filters_all',
        'filters_contragents',
        'filters_contragents_all',
        'task',
        'tasks',
        'task_fc',

        ## expands ##
        'strategy:strategy_to_set:strategy_set',
        'strategy_set:strategy_to_set:task_sets',
        'strategy:strategy_to_set:task',
        'strategy:strategy_item',
        'strategy:strategy_filter',
        'strategy:strategy_to_set',
        'strategy:task',
        'strategy:filters',
        'strategy:strategy_pause',
        'strategy_item:task',
        'strategy_item:task_fc',
        'strategy_item:strategy_item_filter',
        'strategy_item:strategy',
        'strategy_item:task_type',
        'strategy_item:task',
        'strategy_item:task_fc',
        'strategy_item_filter:strategy_item',
        'strategy_to_set:strategy',
        'strategy_filter:strategy',
        'task_type:strategy_item',
        'task_type:task_fc',
        'task_type:task',
        'task:strategy_item',
        'task:strategy',
        'task:task_type',
        'task_fc:strategy_item',
        'task_fc:strategy',
        'task_fc:task_type',
        'filters:strategy',
        'strategy_set:strategy_to_set'
];
